// Generated by scripts/build/generate-hochschulen.mjs from
// https://hs-kompass.de/kompass/xml/download/hs_liste.txt
// DO NOT edit by hand — re-run the generator to refresh.

export interface Hochschule {
  id: number;
  short: string;
  name: string;
  type: string;
  state: string;
}

export const HOCHSCHULEN: Hochschule[] = [
  {
    "id": 354,
    "short": "accadis Hochschule",
    "name": "accadis Hochschule Bad Homburg",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 156,
    "short": "AKAD Hochschule Stuttgart",
    "name": "AKAD Hochschule Stuttgart - staatlich anerkannt",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 187,
    "short": "Akademie der Bildenden Künste München",
    "name": "Akademie der Bildenden Künste München",
    "type": "Künstlerische Hochschulen",
    "state": "Bayern"
  },
  {
    "id": 202,
    "short": "Akademie der Bildenden Künste Nürnberg",
    "name": "Akademie der Bildenden Künste Nürnberg",
    "type": "Künstlerische Hochschulen",
    "state": "Bayern"
  },
  {
    "id": 431,
    "short": "Akkon Hochschule",
    "name": "Akkon-Hochschule",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 349,
    "short": "Alanus Hochschule für Kunst und Gesellschaft",
    "name": "Alanus Hochschule für Kunst und Gesellschaft",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 18,
    "short": "Alice Salomon Hochschule Berlin",
    "name": "Alice Salomon Hochschule Berlin",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 338,
    "short": "Allensbach Hochschule Konstanz",
    "name": "Allensbach Hochschule Konstanz,  staatlich anerkannte Hochschule der European Education Group GmbH",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 361,
    "short": "APOLLON Hochschule der Gesundheitswirtschaft",
    "name": "APOLLON Hochschule der Gesundheitswirtschaft",
    "type": "Fachhochschulen / HAW",
    "state": "Bremen"
  },
  {
    "id": 196,
    "short": "Augustana-Hochschule",
    "name": "Augustana-Hochschule Neuendettelsau",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 437,
    "short": "Bard College Berlin",
    "name": "Bard College Berlin, A Liberal Arts University",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 389,
    "short": "bbw Hochschule",
    "name": "bbw Hochschule",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 279,
    "short": "Bergische Universität Wuppertal",
    "name": "Bergische Universität Wuppertal",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 462,
    "short": "Berlin International University of Applied Sciences",
    "name": "Berlin International University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 15,
    "short": "Berliner Hochschule für Technik",
    "name": "Berliner Hochschule für Technik",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 519,
    "short": "Berufliche Hochschule Hamburg (BHH)",
    "name": "Berufliche Hochschule Hamburg (BHH)",
    "type": "Hochschulen eigenen Typs",
    "state": "Hamburg"
  },
  {
    "id": 422,
    "short": "Brand University of Applied Sciences",
    "name": "Brand University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Hamburg"
  },
  {
    "id": 415,
    "short": "BSP Business and Law School",
    "name": "BSP Business and Law School - Hochschule für Management und Recht",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 45,
    "short": "BTU Cottbus-Senftenberg",
    "name": "Brandenburgische Technische Universität Cottbus-Senftenberg",
    "type": "Universitäten",
    "state": "Brandenburg"
  },
  {
    "id": 326,
    "short": "Bucerius Law School",
    "name": "Bucerius Law School, Hochschule für Rechtswissenschaft",
    "type": "Universitäten",
    "state": "Hamburg"
  },
  {
    "id": 102,
    "short": "Burg Giebichenstein Kunsthochschule",
    "name": "Burg Giebichenstein Kunsthochschule Halle",
    "type": "Künstlerische Hochschulen",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 414,
    "short": "CBS University of Applied Sciences",
    "name": "CBS University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 558,
    "short": "Charlotte Fresenius Hochschule",
    "name": "Charlotte Fresenius Hochschule",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 506,
    "short": "CODE University of Applied Sciences",
    "name": "CODE University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 327,
    "short": "Constructor University",
    "name": "Constructor University",
    "type": "Universitäten",
    "state": "Bremen"
  },
  {
    "id": 591,
    "short": "Deutsche Hochschule für Angewandte Wissenschaften",
    "name": "Deutsche Hochschule für Angewandte Wissenschaften - German University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 383,
    "short": "Deutsche Hochschule für Gesundheit und Sport",
    "name": "DHGS Deutsche Hochschule für Gesundheit und Sport",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 391,
    "short": "Deutsche Hochschule für Prävention und Gesundheitsmanagement",
    "name": "Deutsche Hochschule für Prävention und Gesundheitsmanagement GmbH",
    "type": "Fachhochschulen / HAW",
    "state": "Saarland"
  },
  {
    "id": 148,
    "short": "Deutsche Sporthochschule Köln",
    "name": "Deutsche Sporthochschule Köln",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 516,
    "short": "Digital Business University of Applied Sciences",
    "name": "Digital Business University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 318,
    "short": "DIPLOMA Hochschule Nordhessen",
    "name": "DIPLOMA Hochschule - Private Fachhochschule Nordhessen",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 394,
    "short": "DIU Dresden International University GmbH",
    "name": "DIU - Dresden International University GmbH",
    "type": "Universitäten",
    "state": "Sachsen"
  },
  {
    "id": 398,
    "short": "Duale Hochschule Baden-Württemberg",
    "name": "Duale Hochschule Baden-Württemberg",
    "type": "Hochschulen eigenen Typs",
    "state": "Baden-Württemberg"
  },
  {
    "id": 487,
    "short": "Duale Hochschule Gera-Eisenach",
    "name": "Duale Hochschule Gera-Eisenach",
    "type": "Hochschulen eigenen Typs",
    "state": "Thüringen"
  },
  {
    "id": 727,
    "short": "Duale Hochschule Sachsen",
    "name": "Duale Hochschule Sachsen",
    "type": "Hochschulen eigenen Typs",
    "state": "Sachsen"
  },
  {
    "id": 507,
    "short": "Duale Hochschule Schleswig-Holstein",
    "name": "Duale Hochschule Schleswig-Holstein - staatlich anerkannte Hochschule für angewandte Wissenschaften in Trägerschaft der Wirtschaftsakademie Schleswig-Holstein",
    "type": "Fachhochschulen / HAW",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 206,
    "short": "EBS Universität",
    "name": "EBS Universität für Wirtschaft und Recht",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 658,
    "short": "EHIP - Europäische Hochschule für Innovation und Perspektive",
    "name": "EHIP - Europäische Hochschule für Innovation und Perspektive",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 134,
    "short": "Ernst-Abbe-Hochschule Jena",
    "name": "Ernst-Abbe-Hochschule Jena",
    "type": "Fachhochschulen / HAW",
    "state": "Thüringen"
  },
  {
    "id": 14,
    "short": "ESCP Europe Berlin",
    "name": "ESCP Europe Wirtschaftshochschule Berlin e.V.",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 396,
    "short": "ESMT European School of Management and Technology",
    "name": "ESMT European School of Management and Technology",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 76,
    "short": "Europa-Universität Flensburg",
    "name": "Europa-Universität Flensburg",
    "type": "Universitäten",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 84,
    "short": "Europa-Universität Viadrina Frankfurt (Oder)",
    "name": "Europa-Universität Viadrina Frankfurt (Oder)",
    "type": "Universitäten",
    "state": "Brandenburg"
  },
  {
    "id": 350,
    "short": "Europäische Fernhochschule Hamburg",
    "name": "Europäische Fernhochschule Hamburg",
    "type": "Fachhochschulen / HAW",
    "state": "Hamburg"
  },
  {
    "id": 19,
    "short": "Evangelische Hochschule Berlin",
    "name": "Evangelische Hochschule Berlin",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 55,
    "short": "Evangelische Hochschule Dresden",
    "name": "Evangelische Hochschule Dresden",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen"
  },
  {
    "id": 89,
    "short": "Evangelische Hochschule Freiburg",
    "name": "Evangelische Hochschule Freiburg, staatlich anerkannte Hochschule der Evangelischen Landeskirche in Baden",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 103,
    "short": "Evangelische Hochschule für Kirchenmusik Halle",
    "name": "Evangelische Hochschule für Kirchenmusik",
    "type": "Künstlerische Hochschulen",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 108,
    "short": "Evangelische Hochschule für Soziale Arbeit & Diakonie Hamburg",
    "name": "Evangelische Hochschule für Soziale Arbeit & Diakonie",
    "type": "Fachhochschulen / HAW",
    "state": "Hamburg"
  },
  {
    "id": 48,
    "short": "Evangelische Hochschule Hessen",
    "name": "Evangelische Hochschule Hessen",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 229,
    "short": "Evangelische Hochschule Ludwigsburg",
    "name": "Evangelische Hochschule Ludwigsburg - staatlich anerkannte Hochschule für Angewandte Wissenschaften der Evangelischen Landeskirche Württemberg",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 201,
    "short": "Evangelische Hochschule Nürnberg",
    "name": "Evangelische Hochschule für angewandte Wissenschaften - Evangelische Fachhochschule Nürnberg",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 231,
    "short": "Evangelische Hochschule Rheinland-Westfalen-Lippe",
    "name": "Evangelische Hochschule Rheinland-Westfalen-Lippe",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 426,
    "short": "Evangelische Hochschule Tabor",
    "name": "Evangelische Hochschule Tabor",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 2,
    "short": "Fachhochschule Aachen",
    "name": "Fachhochschule Aachen",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 375,
    "short": "Fachhochschule der Diakonie",
    "name": "Fachhochschule der Diakonie - Diaconia - University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 216,
    "short": "Fachhochschule der Wirtschaft",
    "name": "Fachhochschule der Wirtschaft",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 331,
    "short": "Fachhochschule des Mittelstands",
    "name": "Fachhochschule des Mittelstands (FHM)",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 52,
    "short": "Fachhochschule Dortmund",
    "name": "Fachhochschule Dortmund",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 428,
    "short": "Fachhochschule Dresden",
    "name": "Fachhochschule Dresden",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen"
  },
  {
    "id": 67,
    "short": "Fachhochschule Erfurt",
    "name": "Fachhochschule Erfurt",
    "type": "Fachhochschulen / HAW",
    "state": "Thüringen"
  },
  {
    "id": 311,
    "short": "Fachhochschule für die Wirtschaft Hannover",
    "name": "Fachhochschule für die Wirtschaft Hannover",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 471,
    "short": "Fachhochschule für Finanzen Brandenburg",
    "name": "Fachhochschule für Finanzen Brandenburg",
    "type": "Verwaltungshochschule",
    "state": "Brandenburg"
  },
  {
    "id": 479,
    "short": "Fachhochschule für öffentliche Verwaltung, Polizei und Rechtspflege des Landes Mecklenburg-Vorpommern",
    "name": "Fachhochschule für öffentliche Verwaltung, Polizei und Rechtspflege des Landes Mecklenburg-Vorpommern",
    "type": "Verwaltungshochschule",
    "state": "Mecklenburg-Vorpommern"
  },
  {
    "id": 443,
    "short": "Fachhochschule für Sport und Management Potsdam",
    "name": "Fachhochschule für Sport und Management Potsdam",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 222,
    "short": "Fachhochschule Potsdam",
    "name": "Fachhochschule Potsdam",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 343,
    "short": "Fachhochschule Südwestfalen",
    "name": "Fachhochschule Südwestfalen",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 263,
    "short": "Fachhochschule Wedel",
    "name": "Fachhochschule Wedel",
    "type": "Fachhochschulen / HAW",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 269,
    "short": "Fachhochschule Westküste",
    "name": "Fachhochschule Westküste, Hochschule für Wirtschaft und Technik",
    "type": "Fachhochschulen / HAW",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 70,
    "short": "FAU Erlangen-Nürnberg",
    "name": "Friedrich-Alexander-Universität Erlangen-Nürnberg",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 100,
    "short": "FernUniversität in Hagen",
    "name": "FernUniversität in Hagen",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 192,
    "short": "FH Münster",
    "name": "FH Münster - University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 223,
    "short": "Filmuniversität Babelsberg",
    "name": "Filmuniversität Babelsberg Konrad Wolf",
    "type": "Künstlerische Hochschulen",
    "state": "Brandenburg"
  },
  {
    "id": 433,
    "short": "Fliedner Fachhochschule",
    "name": "Fliedner Fachhochschule Düsseldorf",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 72,
    "short": "Folkwang Universität der Künste",
    "name": "Folkwang Universität der Künste",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 286,
    "short": "FOM Hochschule für Oekonomie & Management",
    "name": "FOM Hochschule für Oekonomie & Management - University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 83,
    "short": "Frankfurt School of Finance & Management",
    "name": "Frankfurt School of Finance & Management",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 79,
    "short": "Frankfurt University of Applied Sciences",
    "name": "Frankfurt University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 11,
    "short": "Freie Universität Berlin",
    "name": "Freie Universität Berlin",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 728,
    "short": "German International University",
    "name": "German International University",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 518,
    "short": "Gisma University of Applied Sciences",
    "name": "Gisma University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 362,
    "short": "HafenCity Universität Hamburg",
    "name": "HafenCity Universität Hamburg",
    "type": "Universitäten",
    "state": "Hamburg"
  },
  {
    "id": 358,
    "short": "Hamburg School of Business Administration",
    "name": "HSBA Hamburg School of Business Administration",
    "type": "Fachhochschulen / HAW",
    "state": "Hamburg"
  },
  {
    "id": 128,
    "short": "HAWK Hochschule für angewandte Wissenschaft und Kunst",
    "name": "HAWK Hochschule für angewandte Wissenschaft und Kunst Hildesheim/Holzminden/Göttingen",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 390,
    "short": "Health Innovation University of Applied Sciences",
    "name": "Health Innovation University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 106,
    "short": "Helmut-Schmidt-Universität/ Universität der Bundeswehr",
    "name": "Helmut-Schmidt-Universität/Universität der Bundeswehr Hamburg",
    "type": "Universitäten",
    "state": "Hamburg"
  },
  {
    "id": 384,
    "short": "Hertie School",
    "name": "Hertie School",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 408,
    "short": "Hessische Hochschule für öffentliches Management und Sicherheit",
    "name": "Hessische Hochschule für öffentliches Management und Sicherheit",
    "type": "Verwaltungshochschule",
    "state": "Hessen"
  },
  {
    "id": 316,
    "short": "HFH Hamburger Fern-Hochschule",
    "name": "Hamburger Fern-Hochschule, gemeinnützige GmbH",
    "type": "Fachhochschulen / HAW",
    "state": "Hamburg"
  },
  {
    "id": 295,
    "short": "HHL Leipzig",
    "name": "HHL Leipzig Graduate School of Management",
    "type": "Universitäten",
    "state": "Sachsen"
  },
  {
    "id": 517,
    "short": "HMU Health and Medical University",
    "name": "HMU Health and Medical University",
    "type": "Hochschulen eigenen Typs",
    "state": "Thüringen"
  },
  {
    "id": 729,
    "short": "HMU Health and Medical University Potsdam",
    "name": "HMU Health and Medical University Potsdam",
    "type": "Hochschulen eigenen Typs",
    "state": "Brandenburg"
  },
  {
    "id": 363,
    "short": "hochschule 21",
    "name": "hochschule 21",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 3,
    "short": "Hochschule Aalen",
    "name": "Hochschule Aalen - Technik, Wirtschaft und Gesundheit",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 4,
    "short": "Hochschule Albstadt-Sigmaringen",
    "name": "Hochschule Albstadt-Sigmaringen",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 5,
    "short": "Hochschule Anhalt",
    "name": "Hochschule Anhalt - Anhalt University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 312,
    "short": "Hochschule Ansbach",
    "name": "Hochschule für angewandte Wissenschaften Ansbach",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 26,
    "short": "Hochschule Biberach",
    "name": "Hochschule Biberach - Architektur und Bauwesen, Betriebswirtschaft und Biotechnologie",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 28,
    "short": "Hochschule Bielefeld",
    "name": "Hochschule Bielefeld - University of Applied Sciences and Arts (HSBI)",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 30,
    "short": "Hochschule Bochum",
    "name": "Hochschule Bochum",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 294,
    "short": "Hochschule Bonn-Rhein-Sieg",
    "name": "Hochschule Bonn-Rhein-Sieg, University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 40,
    "short": "Hochschule Bremen",
    "name": "Hochschule Bremen",
    "type": "Fachhochschulen / HAW",
    "state": "Bremen"
  },
  {
    "id": 41,
    "short": "Hochschule Bremerhaven",
    "name": "Hochschule Bremerhaven",
    "type": "Fachhochschulen / HAW",
    "state": "Bremen"
  },
  {
    "id": 44,
    "short": "Hochschule Coburg",
    "name": "Hochschule für angewandte Wissenschaften Coburg",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 47,
    "short": "Hochschule Darmstadt",
    "name": "Hochschule Darmstadt",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 467,
    "short": "Hochschule der Bayerischen Wirtschaft für angewandte Wissenschaften",
    "name": "Hochschule der Bayerischen Wirtschaft für angewandte Wissenschaften - HDBW",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 454,
    "short": "Hochschule der bildenden Künste Essen",
    "name": "Hochschule der bildenden Künste (HBK) Essen",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 239,
    "short": "Hochschule der Bildenden Künste Saar",
    "name": "Hochschule der Bildenden Künste Saar",
    "type": "Künstlerische Hochschulen",
    "state": "Saarland"
  },
  {
    "id": 250,
    "short": "Hochschule der Medien Stuttgart",
    "name": "Hochschule der Medien Stuttgart",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 432,
    "short": "Hochschule der Wirtschaft für Management",
    "name": "Hochschule der Wirtschaft für Management",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 469,
    "short": "Hochschule des Bundes für öffentliche Verwaltung",
    "name": "Hochschule des Bundes für öffentliche Verwaltung",
    "type": "Verwaltungshochschule",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 60,
    "short": "Hochschule Düsseldorf",
    "name": "Hochschule Düsseldorf",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 405,
    "short": "Hochschule Emden/ Leer",
    "name": "Hochschule Emden/Leer",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 73,
    "short": "Hochschule Esslingen",
    "name": "Hochschule Esslingen",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 77,
    "short": "Hochschule Flensburg",
    "name": "Hochschule Flensburg",
    "type": "Fachhochschulen / HAW",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 271,
    "short": "Hochschule Fresenius",
    "name": "Hochschule Fresenius",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 440,
    "short": "Hochschule Fresenius Heidelberg",
    "name": "Hochschule Fresenius Heidelberg  staatlich anerkannte Hochschule der Hochschule Fresenius für Internationales Management GmbH",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 92,
    "short": "Hochschule Fulda",
    "name": "Hochschule Fulda - University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 107,
    "short": "Hochschule für Angewandte Wissenschaften Hamburg",
    "name": "Hochschule für Angewandte Wissenschaften Hamburg",
    "type": "Fachhochschulen / HAW",
    "state": "Hamburg"
  },
  {
    "id": 145,
    "short": "Hochschule für Angewandte Wissenschaften Kiel",
    "name": "Hochschule für Angewandte Wissenschaften Kiel",
    "type": "Fachhochschulen / HAW",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 369,
    "short": "Hochschule für angewandtes Management",
    "name": "Hochschule für angewandtes Management",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 80,
    "short": "Hochschule für Bildende Künste",
    "name": "Hochschule für Bildende Künste (Städelschule)",
    "type": "Künstlerische Hochschulen",
    "state": "Hessen"
  },
  {
    "id": 37,
    "short": "Hochschule für Bildende Künste Braunschweig",
    "name": "Hochschule für Bildende Künste Braunschweig",
    "type": "Künstlerische Hochschulen",
    "state": "Niedersachsen"
  },
  {
    "id": 56,
    "short": "Hochschule für Bildende Künste Dresden",
    "name": "Hochschule für Bildende Künste Dresden",
    "type": "Künstlerische Hochschulen",
    "state": "Sachsen"
  },
  {
    "id": 109,
    "short": "Hochschule für Bildende Künste Hamburg",
    "name": "Hochschule für Bildende Künste Hamburg",
    "type": "Künstlerische Hochschulen",
    "state": "Hamburg"
  },
  {
    "id": 339,
    "short": "Hochschule für Evangelische Kirchenmusik",
    "name": "Hochschule für evangelische Kirchenmusik der Evangelisch-Lutherischen Kirche in Bayern",
    "type": "Künstlerische Hochschulen",
    "state": "Bayern"
  },
  {
    "id": 190,
    "short": "Hochschule für Fernsehen und Film",
    "name": "Hochschule für Fernsehen und Film München",
    "type": "Künstlerische Hochschulen",
    "state": "Bayern"
  },
  {
    "id": 488,
    "short": "Hochschule für Finanzen NRW",
    "name": "Hochschule für Finanzen NRW",
    "type": "Verwaltungshochschule",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 352,
    "short": "Hochschule für Finanzwirtschaft & Management",
    "name": "Hochschule für Finanzwirtschaft & Management",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 300,
    "short": "Hochschule für Forstwirtschaft Rottenburg",
    "name": "Hochschule für Forstwirtschaft Rottenburg",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 468,
    "short": "Hochschule für Gesellschaftsgestaltung",
    "name": "Hochschule für Gesellschaftsgestaltung",
    "type": "Hochschulen eigenen Typs",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 207,
    "short": "Hochschule für Gestaltung Offenbach",
    "name": "Hochschule für Gestaltung Offenbach",
    "type": "Künstlerische Hochschulen",
    "state": "Hessen"
  },
  {
    "id": 244,
    "short": "Hochschule für Gestaltung Schwäbisch Gmünd",
    "name": "Hochschule für Gestaltung Schwäbisch Gmünd",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 692,
    "short": "Hochschule für Gesundheitsfachberufe Eberswalde",
    "name": "Hochschule für Gesundheitsfachberufe Eberswalde",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 164,
    "short": "Hochschule für Grafik und Buchkunst Leipzig",
    "name": "Hochschule für Grafik und Buchkunst Leipzig",
    "type": "Künstlerische Hochschulen",
    "state": "Sachsen"
  },
  {
    "id": 121,
    "short": "Hochschule für Jüdische Studien",
    "name": "Hochschule für Jüdische Studien Heidelberg",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 346,
    "short": "Hochschule für Katholische Kirchenmusik und Musikpädagogik",
    "name": "Hochschule für Katholische Kirchenmusik und Musikpädagogik",
    "type": "Künstlerische Hochschulen",
    "state": "Bayern"
  },
  {
    "id": 241,
    "short": "Hochschule für Katholische Theologie",
    "name": "Kölner Hochschule für Katholische Theologie (KHKT)",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 126,
    "short": "Hochschule für Kirchenmusik der Evangelischen Kirche von Westfalen",
    "name": "Hochschule für Kirchenmusik der Evangelischen Kirche von Westfalen",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 58,
    "short": "Hochschule für Kirchenmusik Dresden",
    "name": "Hochschule für Kirchenmusik der Evangelisch-Lutherischen Landeskirche Sachsens",
    "type": "Künstlerische Hochschulen",
    "state": "Sachsen"
  },
  {
    "id": 124,
    "short": "Hochschule für Kirchenmusik Heidelberg",
    "name": "Hochschule für Kirchenmusik der Evangelischen Landeskirche in Baden",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 325,
    "short": "Hochschule für Kirchenmusik Rottenburg",
    "name": "Hochschule für Kirchenmusik der Diözese Rottenburg-Stuttgart",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 75,
    "short": "Hochschule für Kirchenmusik Tübingen",
    "name": "Hochschule für Kirchenmusik der Evangelischen Landeskirche in Württemberg",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 39,
    "short": "Hochschule für Künste Bremen",
    "name": "Hochschule für Künste Bremen",
    "type": "Künstlerische Hochschulen",
    "state": "Bremen"
  },
  {
    "id": 213,
    "short": "Hochschule für Künste im Sozialen",
    "name": "Hochschule für Künste im Sozialen, Ottersberg",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 21,
    "short": "Hochschule für Musik Berlin",
    "name": "\"Hochschule für Musik Hanns Eisler Berlin\"",
    "type": "Künstlerische Hochschulen",
    "state": "Berlin"
  },
  {
    "id": 49,
    "short": "Hochschule für Musik Detmold",
    "name": "Hochschule für Musik Detmold",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 57,
    "short": "Hochschule für Musik Dresden",
    "name": "Hochschule für Musik Carl Maria von Weber Dresden",
    "type": "Künstlerische Hochschulen",
    "state": "Sachsen"
  },
  {
    "id": 90,
    "short": "Hochschule für Musik Freiburg",
    "name": "Hochschule für Musik Freiburg im Breisgau",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 141,
    "short": "Hochschule für Musik Karlsruhe",
    "name": "Hochschule für Musik Karlsruhe",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 321,
    "short": "Hochschule für Musik Nürnberg",
    "name": "Hochschule für Musik Nürnberg",
    "type": "Künstlerische Hochschulen",
    "state": "Bayern"
  },
  {
    "id": 240,
    "short": "Hochschule für Musik Saar",
    "name": "Hochschule für Musik Saar",
    "type": "Künstlerische Hochschulen",
    "state": "Saarland"
  },
  {
    "id": 81,
    "short": "Hochschule für Musik und Darstellende Kunst Frankfurt am Main",
    "name": "Hochschule für Musik und Darstellende Kunst Frankfurt am Main",
    "type": "Künstlerische Hochschulen",
    "state": "Hessen"
  },
  {
    "id": 123,
    "short": "Hochschule für Musik und Darstellende Kunst Mannheim",
    "name": "Staatliche Hochschule für Musik und Darstellende Kunst Mannheim",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 254,
    "short": "Hochschule für Musik und Darstellende Kunst Stuttgart",
    "name": "Staatliche Hochschule für Musik und Darstellende Kunst Stuttgart",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 153,
    "short": "Hochschule für Musik und Tanz Köln",
    "name": "Hochschule für Musik und Tanz Köln",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 110,
    "short": "Hochschule für Musik und Theater Hamburg",
    "name": "Hochschule für Musik und Theater Hamburg",
    "type": "Künstlerische Hochschulen",
    "state": "Hamburg"
  },
  {
    "id": 162,
    "short": "Hochschule für Musik und Theater Leipzig",
    "name": "\"Hochschule für Musik und Theater Felix Mendelssohn Bartholdy Leipzig\"",
    "type": "Künstlerische Hochschulen",
    "state": "Sachsen"
  },
  {
    "id": 188,
    "short": "Hochschule für Musik und Theater München",
    "name": "Hochschule für Musik und Theater München",
    "type": "Künstlerische Hochschulen",
    "state": "Bayern"
  },
  {
    "id": 234,
    "short": "Hochschule für Musik und Theater Rostock",
    "name": "Hochschule für Musik und Theater Rostock",
    "type": "Künstlerische Hochschulen",
    "state": "Mecklenburg-Vorpommern"
  },
  {
    "id": 267,
    "short": "Hochschule für Musik Weimar",
    "name": "Hochschule für Musik Franz Liszt Weimar",
    "type": "Künstlerische Hochschulen",
    "state": "Thüringen"
  },
  {
    "id": 278,
    "short": "Hochschule für Musik Würzburg",
    "name": "Hochschule für Musik Würzburg",
    "type": "Künstlerische Hochschulen",
    "state": "Bayern"
  },
  {
    "id": 117,
    "short": "Hochschule für Musik, Theater und Medien Hannover",
    "name": "Hochschule für Musik, Theater und Medien Hannover",
    "type": "Künstlerische Hochschulen",
    "state": "Niedersachsen"
  },
  {
    "id": 64,
    "short": "Hochschule für nachhaltige Entwicklung",
    "name": "Hochschule für nachhaltige Entwicklung Eberswalde",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 470,
    "short": "Hochschule für Öffentliche Verwaltung Bremen",
    "name": "Hochschule für Öffentliche Verwaltung Bremen",
    "type": "Verwaltungshochschule",
    "state": "Bremen"
  },
  {
    "id": 189,
    "short": "Hochschule für Philosophie",
    "name": "Hochschule für Philosophie",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 504,
    "short": "Hochschule für Polizei Baden-Württemberg",
    "name": "Hochschule für Polizei Baden-Württemberg",
    "type": "Verwaltungshochschule",
    "state": "Baden-Württemberg"
  },
  {
    "id": 484,
    "short": "Hochschule für Polizei und öffentliche Verwaltung Nordrhein-Westfalen",
    "name": "Hochschule für Polizei und öffentliche Verwaltung Nordrhein-Westfalen",
    "type": "Verwaltungshochschule",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 23,
    "short": "Hochschule für Schauspielkunst Berlin",
    "name": "Hochschule für Schauspielkunst Ernst Busch",
    "type": "Künstlerische Hochschulen",
    "state": "Berlin"
  },
  {
    "id": 458,
    "short": "Hochschule für Soziale Arbeit und Pädagogik",
    "name": "Hochschule für Soziale Arbeit und Pädagogik (HSAP) gemeinnützige Betriebsgesellschaft mbH",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 251,
    "short": "Hochschule für Technik Stuttgart",
    "name": "Hochschule für Technik Stuttgart",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 16,
    "short": "Hochschule für Technik und Wirtschaft Berlin",
    "name": "Hochschule für Technik und Wirtschaft Berlin",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 236,
    "short": "Hochschule für Technik und Wirtschaft des Saarlandes",
    "name": "Hochschule für Technik und Wirtschaft des Saarlandes",
    "type": "Fachhochschulen / HAW",
    "state": "Saarland"
  },
  {
    "id": 54,
    "short": "Hochschule für Technik und Wirtschaft Dresden",
    "name": "Hochschule für Technik und Wirtschaft Dresden - University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen"
  },
  {
    "id": 160,
    "short": "Hochschule für Technik, Wirtschaft und Kultur Leipzig",
    "name": "Hochschule für Technik, Wirtschaft und Kultur Leipzig",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen"
  },
  {
    "id": 208,
    "short": "Hochschule für Technik, Wirtschaft und Medien Offenburg",
    "name": "Hochschule für Technik, Wirtschaft und Medien Offenburg",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 307,
    "short": "Hochschule für Wirtschaft und Gesellschaft Ludwigshafen",
    "name": "Hochschule für Wirtschaft und Gesellschaft Ludwigshafen",
    "type": "Fachhochschulen / HAW",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 17,
    "short": "Hochschule für Wirtschaft und Recht Berlin",
    "name": "Hochschule für Wirtschaft und Recht Berlin",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 203,
    "short": "Hochschule für Wirtschaft und Umwelt Nürtingen-Geislingen",
    "name": "Hochschule für Wirtschaft und Umwelt Nürtingen-Geislingen",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 94,
    "short": "Hochschule Furtwangen",
    "name": "Hochschule Furtwangen - Informatik, Technik, Wirtschaft, Medien, Gesundheit",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 446,
    "short": "Hochschule Geisenheim",
    "name": "Hochschule Geisenheim",
    "type": "Hochschulen eigenen Typs",
    "state": "Hessen"
  },
  {
    "id": 399,
    "short": "Hochschule Hamm-Lippstadt",
    "name": "Hochschule Hamm-Lippstadt",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 115,
    "short": "Hochschule Hannover",
    "name": "Hochschule Hannover",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 118,
    "short": "Hochschule Harz",
    "name": "Hochschule Harz, Hochschule für angewandte Wissenschaften (FH)",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 125,
    "short": "Hochschule Heilbronn",
    "name": "Hochschule Heilbronn, Technik, Wirtschaft, Informatik",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 287,
    "short": "Hochschule Hof",
    "name": "Hochschule für angewandte Wissenschaften Hof",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 306,
    "short": "Hochschule Kaiserslautern",
    "name": "Hochschule Kaiserslautern (University of Applied Sciences)",
    "type": "Fachhochschulen / HAW",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 138,
    "short": "Hochschule Karlsruhe",
    "name": "Hochschule Karlsruhe - Technik und Wirtschaft",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 143,
    "short": "Hochschule Kempten",
    "name": "Hochschule für angewandte Wissenschaften Kempten",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 305,
    "short": "Hochschule Koblenz",
    "name": "Hochschule Koblenz",
    "type": "Fachhochschulen / HAW",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 155,
    "short": "Hochschule Konstanz",
    "name": "Hochschule Konstanz Technik, Wirtschaft und Gestaltung",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 157,
    "short": "Hochschule Landshut",
    "name": "Hochschule Landshut - Hochschule für angewandte Wissenschaften",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 173,
    "short": "Hochschule Magdeburg-Stendal",
    "name": "Hochschule Magdeburg-Stendal",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 310,
    "short": "Hochschule Mainz",
    "name": "Hochschule Mainz",
    "type": "Fachhochschulen / HAW",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 498,
    "short": "Hochschule Meißen (FH) und Fortbildungszentrum",
    "name": "Hochschule für öffentliche Verwaltung und Rechtspflege (FH), Fortbildungszentrum des Freistaates Sachsen (HSF)",
    "type": "Verwaltungshochschule",
    "state": "Sachsen"
  },
  {
    "id": 180,
    "short": "Hochschule Merseburg",
    "name": "Hochschule Merseburg",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 181,
    "short": "Hochschule Mittweida",
    "name": "Hochschule Mittweida, University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen"
  },
  {
    "id": 291,
    "short": "Hochschule München",
    "name": "Hochschule für angewandte Wissenschaften München",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 319,
    "short": "Hochschule Neu-Ulm",
    "name": "Hochschule für angewandte Wissenschaften Neu-Ulm",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 195,
    "short": "Hochschule Neubrandenburg",
    "name": "Hochschule Neubrandenburg - University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Mecklenburg-Vorpommern"
  },
  {
    "id": 197,
    "short": "Hochschule Niederrhein",
    "name": "Hochschule Niederrhein",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 315,
    "short": "Hochschule Nordhausen",
    "name": "Hochschule Nordhausen",
    "type": "Fachhochschulen / HAW",
    "state": "Thüringen"
  },
  {
    "id": 214,
    "short": "Hochschule Osnabrück",
    "name": "Hochschule Osnabrück",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 219,
    "short": "Hochschule Pforzheim",
    "name": "Hochschule Pforzheim - Gestaltung, Technik, Wirtschaft und Recht",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 224,
    "short": "Hochschule Ravensburg-Weingarten",
    "name": "Hochschule Ravensburg-Weingarten",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 227,
    "short": "Hochschule Reutlingen",
    "name": "Hochschule Reutlingen, Hochschule für Technik-  Wirtschaft-Informatik-Design",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 400,
    "short": "Hochschule Rhein-Waal",
    "name": "Hochschule Rhein-Waal - University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 270,
    "short": "Hochschule RheinMain",
    "name": "Hochschule RheinMain",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 409,
    "short": "Hochschule Ruhr West",
    "name": "Hochschule Ruhr West- University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 242,
    "short": "Hochschule Schmalkalden",
    "name": "Hochschule Schmalkalden",
    "type": "Fachhochschulen / HAW",
    "state": "Thüringen"
  },
  {
    "id": 247,
    "short": "Hochschule Stralsund",
    "name": "Hochschule Stralsund",
    "type": "Fachhochschulen / HAW",
    "state": "Mecklenburg-Vorpommern"
  },
  {
    "id": 308,
    "short": "Hochschule Trier",
    "name": "Hochschule Trier - Trier University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 264,
    "short": "Hochschule Weihenstephan-Triesdorf",
    "name": "Hochschule für angewandte Wissenschaften Weihenstephan-Triesdorf",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 427,
    "short": "Hochschule Weserbergland",
    "name": "Hochschule Weserbergland",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 274,
    "short": "Hochschule Wismar",
    "name": "Hochschule Wismar - University of Applied Sciences: Technology, Business and Design",
    "type": "Fachhochschulen / HAW",
    "state": "Mecklenburg-Vorpommern"
  },
  {
    "id": 309,
    "short": "Hochschule Worms",
    "name": "Hochschule Worms, University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 282,
    "short": "Hochschule Zittau/ Görlitz",
    "name": "Hochschule Zittau/Görlitz",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen"
  },
  {
    "id": 455,
    "short": "HSD Hochschule Döpfer",
    "name": "HSD Hochschule Döpfer",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 12,
    "short": "Humboldt-Universität zu Berlin",
    "name": "Humboldt-Universität zu Berlin",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 401,
    "short": "International Psychoanalytic University",
    "name": "International Psychoanalytic University Berlin",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 285,
    "short": "International School of Management",
    "name": "International School of Management",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 434,
    "short": "Internationale Hochschule Liebenzell",
    "name": "Internationale Hochschule Liebenzell (IHL)",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 376,
    "short": "Internationale Hochschule SDI",
    "name": "Internationale Hochschule SDI München - Hochschule für angewandte Wissenschaften",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 525,
    "short": "INU - Innovative University of Applied Sciences",
    "name": "INU - Innovative University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 449,
    "short": "IST-Hochschule für Management",
    "name": "IST-Hochschule für Management",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 329,
    "short": "IU Internationale Hochschule",
    "name": "IU Internationale Hochschule",
    "type": "Fachhochschulen / HAW",
    "state": "Thüringen"
  },
  {
    "id": 406,
    "short": "Jade Hochschule",
    "name": "Jade Hochschule -  Wilhelmshaven/Oldenburg/Elsfleth",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 359,
    "short": "Karlshochschule International University",
    "name": "Karlshochschule International University - staatlich anerkannte Hochschule der Karlshochschule gemeinnützige GmbH Karlsruhe",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 136,
    "short": "Karlsruher Institut für Technologie",
    "name": "Karlsruher Institut für Technologie",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 88,
    "short": "Katholische Hochschule Freiburg",
    "name": "Katholische Hochschule Freiburg, staatlich anerkannte Hochschule - Catholic University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 24,
    "short": "Katholische Hochschule für Sozialwesen Berlin",
    "name": "Katholische Hochschule für Sozialwesen Berlin (KHSB) - Staatlich anerkannte Fachhochschule für Sozialwesen",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 175,
    "short": "Katholische Hochschule Mainz",
    "name": "Katholische Hochschule Mainz Catholic University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 151,
    "short": "Katholische Hochschule Nordrhein-Westfalen",
    "name": "Katholische Hochschule Nordrhein-Westfalen - Catholic University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 186,
    "short": "Katholische Stiftungshochschule München",
    "name": "\"Katholische    Stiftungshochschule für   angewandte Wissenschaften München - Hochschule der Kirchlichen Stiftung des öffentlichen Rechts Katholische Bildungsstätten für Sozialberufe in Bayern\"",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 65,
    "short": "Katholische Universität Eichstätt - Ingolstadt",
    "name": "Katholische Universität Eichstätt - Ingolstadt",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 281,
    "short": "Kirchliche Hochschule Wuppertal",
    "name": "Kirchliche Hochschule Wuppertal",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 520,
    "short": "Kolping Hochschule für Gesundheit und Soziales Köln",
    "name": "Kolping Hochschule",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 429,
    "short": "Kühne Logistics University",
    "name": "Kühne Logistics University - Wissenschaftliche Hochschule für Logistik und Unternehmensführung",
    "type": "Universitäten",
    "state": "Hamburg"
  },
  {
    "id": 61,
    "short": "Kunstakademie Düsseldorf",
    "name": "Kunstakademie Düsseldorf",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 139,
    "short": "Kunstakademie Karlsruhe",
    "name": "Staatliche Akademie der Bildenden Künste Karlsruhe",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 193,
    "short": "Kunstakademie Münster",
    "name": "Kunstakademie Münster, Hochschule für Bildende Künste",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 152,
    "short": "Kunsthochschule für Medien Köln",
    "name": "Kunsthochschule für Medien Köln",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 114,
    "short": "Leibniz Universität Hannover",
    "name": "Gottfried Wilhelm Leibniz Universität Hannover",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 439,
    "short": "Leibniz-Fachhochschule Hannover",
    "name": "Leibniz-Fachhochschule",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 171,
    "short": "Leuphana Universität",
    "name": "Leuphana Universität Lüneburg",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 183,
    "short": "LMU München",
    "name": "Ludwig-Maximilians-Universität München",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 205,
    "short": "Lutherische Theologische Hochschule Oberursel",
    "name": "Lutherische Theologische Hochschule Oberursel",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 366,
    "short": "Macromedia University of Applied Sciences",
    "name": "Macromedia University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 353,
    "short": "Mediadesign Hochschule",
    "name": "Mediadesign Hochschule für Design und Informatik",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 448,
    "short": "Medical School Berlin",
    "name": "Medical School Berlin - Hochschule für Gesundheit und Medizin (MSB)",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 421,
    "short": "Medical School Hamburg",
    "name": "MSH Medical School Hamburg - University of Applied Sciences and Medical University",
    "type": "Hochschulen eigenen Typs",
    "state": "Hamburg"
  },
  {
    "id": 463,
    "short": "Medizinische Hochschule Brandenburg Theodor Fontane",
    "name": "Medizinische Hochschule Brandenburg Theodor Fontane",
    "type": "Universitäten",
    "state": "Brandenburg"
  },
  {
    "id": 112,
    "short": "Medizinische Hochschule Hannover",
    "name": "Medizinische Hochschule Hannover (MHH)",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 762,
    "short": "Medizinische Universität Lausitz - Carl Thiem",
    "name": "Medizinische Universität Lausitz - Carl Thiem",
    "type": "Universitäten",
    "state": "Brandenburg"
  },
  {
    "id": 252,
    "short": "Merz Akademie Stuttgart",
    "name": "Merz Akademie Hochschule für Gestaltung, Kunst und Medien, Stuttgart - Staatlich anerkannt",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 420,
    "short": "MU Media University of Applied Sciences",
    "name": "MU Media University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Berlin"
  },
  {
    "id": 336,
    "short": "Munich Business School",
    "name": "Munich Business School - Staatlich anerkannte private Fachhochschule",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 170,
    "short": "Musikhochschule Lübeck",
    "name": "Musikhochschule Lübeck",
    "type": "Künstlerische Hochschulen",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 289,
    "short": "Muthesius Kunsthochschule",
    "name": "Muthesius Kunsthochschule",
    "type": "Künstlerische Hochschulen",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 220,
    "short": "NORDAKADEMIE Hochschule der Wirtschaft",
    "name": "NORDAKADEMIE Hochschule der Wirtschaft",
    "type": "Fachhochschulen / HAW",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 460,
    "short": "Northern Business School",
    "name": "NBS Northern Business School  University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Hamburg"
  },
  {
    "id": 280,
    "short": "Ostbayerische Technische Hochschule Amberg-Weiden",
    "name": "Ostbayerische Technische Hochschule Amberg-Weiden",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 226,
    "short": "Ostbayerische Technische Hochschule Regensburg",
    "name": "Ostbayerische Technische Hochschule Regensburg",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 36,
    "short": "Ostfalia Hochschule",
    "name": "Hochschule Braunschweig/Wolfenbüttel, Ostfalia Hochschule für angewandte Wissenschaften",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 87,
    "short": "Pädagogische Hochschule Freiburg",
    "name": "Pädagogische Hochschule Freiburg",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 120,
    "short": "Pädagogische Hochschule Heidelberg",
    "name": "Pädagogische Hochschule Heidelberg",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 137,
    "short": "Pädagogische Hochschule Karlsruhe",
    "name": "Pädagogische Hochschule Karlsruhe",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 166,
    "short": "Pädagogische Hochschule Ludwigsburg",
    "name": "Pädagogische Hochschule Ludwigsburg",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 243,
    "short": "Pädagogische Hochschule Schwäbisch Gmünd",
    "name": "Pädagogische Hochschule Schwäbisch Gmünd",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 268,
    "short": "Pädagogische Hochschule Weingarten",
    "name": "Pädagogische Hochschule Weingarten",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 324,
    "short": "Palucca Hochschule für Tanz",
    "name": "Palucca Hochschule für Tanz Dresden",
    "type": "Künstlerische Hochschulen",
    "state": "Sachsen"
  },
  {
    "id": 82,
    "short": "Philosophisch-Theologische Hochschule Frankfurt am Main",
    "name": "Philosophisch-Theologische Hochschule Sankt Georgen Frankfurt am Main",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 194,
    "short": "Philosophisch-Theologische Hochschule Münster",
    "name": "Philosophisch-Theologische Hochschule Münster - Kirchlich und staatlich anerkannte Hochschule in Trägerschaft der PTH Philosophisch-Theologische Hochschule Münster gemeinnützige GmbH",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 320,
    "short": "PHWT Vechta/Diepholz",
    "name": "Private Hochschule für Wirtschaft und Technik Vechta/Diepholz",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 299,
    "short": "Private Hochschule Göttingen",
    "name": "PFH - Private Hochschule Göttingen",
    "type": "Fachhochschulen / HAW",
    "state": "Niedersachsen"
  },
  {
    "id": 441,
    "short": "Psychologische Hochschule Berlin",
    "name": "Psychologische Hochschule Berlin (PHB)",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 150,
    "short": "Rheinische Hochschule",
    "name": "Rheinische Hochschule Köln",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 62,
    "short": "Robert Schumann Hochschule",
    "name": "Robert Schumann Hochschule Düsseldorf",
    "type": "Künstlerische Hochschulen",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 135,
    "short": "RPTU Kaiserslautern-Landau",
    "name": "Rheinland-Pfälzische Technische Universität Kaiserslautern-Landau",
    "type": "Universitäten",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 1,
    "short": "RWTH Aachen",
    "name": "Rheinisch-Westfälische Technische Hochschule Aachen",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 313,
    "short": "SRH Fernhochschule - The Mobile University",
    "name": "SRH Fernhochschule - The Mobile University",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 122,
    "short": "SRH Heidelberg",
    "name": "SRH University of Applied Sciences Heidelberg",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 253,
    "short": "Staatliche Akademie der Bildenden Künste Stuttgart",
    "name": "Staatliche Akademie der Bildenden Künste Stuttgart",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 140,
    "short": "Staatliche Hochschule für Gestaltung Karlsruhe",
    "name": "Staatliche Hochschule für Gestaltung Karlsruhe",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 257,
    "short": "Staatliche Hochschule für Musik Trossingen",
    "name": "Staatliche Hochschule für Musik Trossingen",
    "type": "Künstlerische Hochschulen",
    "state": "Baden-Württemberg"
  },
  {
    "id": 330,
    "short": "Steinbeis Hochschule",
    "name": "Steinbeis Hochschule",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 333,
    "short": "Technische Hochschule Aschaffenburg",
    "name": "Technische Hochschule Aschaffenburg",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 7,
    "short": "Technische Hochschule Augsburg",
    "name": "Technische Hochschule Augsburg",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 304,
    "short": "Technische Hochschule Bingen",
    "name": "Technische Hochschule Bingen",
    "type": "Fachhochschulen / HAW",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 34,
    "short": "Technische Hochschule Brandenburg",
    "name": "Technische Hochschule Brandenburg",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 284,
    "short": "Technische Hochschule Deggendorf",
    "name": "Technische Hochschule Deggendorf",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 31,
    "short": "Technische Hochschule Georg Agricola",
    "name": "Technische Hochschule Georg Agricola",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 288,
    "short": "Technische Hochschule Ingolstadt",
    "name": "Technische Hochschule Ingolstadt",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 149,
    "short": "Technische Hochschule Köln",
    "name": "Technische Hochschule Köln",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 169,
    "short": "Technische Hochschule Lübeck",
    "name": "Technische Hochschule Lübeck",
    "type": "Fachhochschulen / HAW",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 177,
    "short": "Technische Hochschule Mannheim",
    "name": "Technische Hochschule Mannheim",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 97,
    "short": "Technische Hochschule Mittelhessen",
    "name": "Technische Hochschule Mittelhessen - THM",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 200,
    "short": "Technische Hochschule Nürnberg",
    "name": "Technische Hochschule Nürnberg Georg Simon Ohm",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 165,
    "short": "Technische Hochschule Ostwestfalen-Lippe",
    "name": "Technische Hochschule Ostwestfalen-Lippe",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 232,
    "short": "Technische Hochschule Rosenheim",
    "name": "Technische Hochschule Rosenheim",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 260,
    "short": "Technische Hochschule Ulm",
    "name": "Technische Hochschule Ulm",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 272,
    "short": "Technische Hochschule Wildau",
    "name": "Technische Hochschule Wildau",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 277,
    "short": "Technische Hochschule Würzburg-Schweinfurt",
    "name": "Technische Hochschule Würzburg-Schweinfurt",
    "type": "Fachhochschulen / HAW",
    "state": "Bayern"
  },
  {
    "id": 691,
    "short": "Technische Universität Nürnberg",
    "name": "Technische Universität Nürnberg",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 93,
    "short": "Theologische Fakultät Fulda",
    "name": "Theologische Fakultät Fulda",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 217,
    "short": "Theologische Fakultät Paderborn",
    "name": "Theologische Fakultät Paderborn",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 256,
    "short": "Theologische Fakultät Trier",
    "name": "Theologische Fakultät Trier",
    "type": "Universitäten",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 407,
    "short": "Theologische Hochschule Elstal",
    "name": "Theologische Hochschule Elstal",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 447,
    "short": "Theologische Hochschule Ewersbach",
    "name": "Theologische Hochschule Ewersbach",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 91,
    "short": "Theologische Hochschule Friedensau",
    "name": "Theologische Hochschule Friedensau",
    "type": "Universitäten",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 360,
    "short": "Theologische Hochschule Reutlingen",
    "name": "Theologische Hochschule Reutlingen - staatlich anerkannte Fachhochschule der Evangelisch-methodistischen Kirche",
    "type": "Fachhochschulen / HAW",
    "state": "Baden-Württemberg"
  },
  {
    "id": 113,
    "short": "Tierärztliche Hochschule Hannover",
    "name": "Stiftung Tierärztliche Hochschule Hannover",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 657,
    "short": "Tomorrow University of Applied Sciences",
    "name": "Tomorrow University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 85,
    "short": "TU Bergakademie Freiberg",
    "name": "Technische Universität Bergakademie Freiberg",
    "type": "Universitäten",
    "state": "Sachsen"
  },
  {
    "id": 13,
    "short": "TU Berlin",
    "name": "Technische Universität Berlin",
    "type": "Universitäten",
    "state": "Berlin"
  },
  {
    "id": 35,
    "short": "TU Braunschweig",
    "name": "Technische Universität Braunschweig",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 42,
    "short": "TU Chemnitz",
    "name": "Technische Universität Chemnitz",
    "type": "Universitäten",
    "state": "Sachsen"
  },
  {
    "id": 43,
    "short": "TU Clausthal",
    "name": "Technische Universität Clausthal",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 46,
    "short": "TU Darmstadt",
    "name": "Technische Universität Darmstadt",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 51,
    "short": "TU Dortmund",
    "name": "Technische Universität Dortmund",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 53,
    "short": "TU Dresden",
    "name": "Technische Universität Dresden",
    "type": "Universitäten",
    "state": "Sachsen"
  },
  {
    "id": 105,
    "short": "TU Hamburg",
    "name": "Technische Universität Hamburg",
    "type": "Universitäten",
    "state": "Hamburg"
  },
  {
    "id": 130,
    "short": "TU Ilmenau",
    "name": "Technische Universität Ilmenau",
    "type": "Universitäten",
    "state": "Thüringen"
  },
  {
    "id": 184,
    "short": "TU München",
    "name": "Technische Universität München",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 6,
    "short": "Universität Augsburg",
    "name": "Universität Augsburg",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 8,
    "short": "Universität Bamberg",
    "name": "Otto-Friedrich-Universität Bamberg",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 9,
    "short": "Universität Bayreuth",
    "name": "Universität Bayreuth",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 27,
    "short": "Universität Bielefeld",
    "name": "Universität Bielefeld",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 29,
    "short": "Universität Bochum",
    "name": "Ruhr-Universität Bochum",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 32,
    "short": "Universität Bonn",
    "name": "Rheinische Friedrich-Wilhelms-Universität Bonn",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 38,
    "short": "Universität Bremen",
    "name": "Universität Bremen",
    "type": "Universitäten",
    "state": "Bremen"
  },
  {
    "id": 185,
    "short": "Universität der Bundeswehr München",
    "name": "Universität der Bundeswehr München",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 20,
    "short": "Universität der Künste Berlin",
    "name": "Universität der Künste Berlin",
    "type": "Künstlerische Hochschulen",
    "state": "Berlin"
  },
  {
    "id": 235,
    "short": "Universität des Saarlandes",
    "name": "Universität des Saarlandes",
    "type": "Universitäten",
    "state": "Saarland"
  },
  {
    "id": 71,
    "short": "Universität Duisburg-Essen",
    "name": "Universität Duisburg-Essen",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 59,
    "short": "Universität Düsseldorf",
    "name": "Heinrich-Heine-Universität Düsseldorf",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 66,
    "short": "Universität Erfurt",
    "name": "Universität Erfurt",
    "type": "Universitäten",
    "state": "Thüringen"
  },
  {
    "id": 78,
    "short": "Universität Frankfurt am Main",
    "name": "Johann Wolfgang Goethe-Universität, Frankfurt am Main",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 86,
    "short": "Universität Freiburg im Breisgau",
    "name": "Albert-Ludwigs-Universität Freiburg im Breisgau",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 246,
    "short": "Universität für Verwaltungswissenschaften Speyer",
    "name": "Deutsche Universität für Verwaltungswissenschaften Speyer",
    "type": "Universitäten",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 96,
    "short": "Universität Giessen",
    "name": "Justus-Liebig-Universität Gießen",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 98,
    "short": "Universität Göttingen",
    "name": "Georg-August-Universität Göttingen",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 99,
    "short": "Universität Greifswald",
    "name": "Universität Greifswald",
    "type": "Universitäten",
    "state": "Mecklenburg-Vorpommern"
  },
  {
    "id": 101,
    "short": "Universität Halle-Wittenberg",
    "name": "Martin-Luther-Universität Halle-Wittenberg",
    "type": "Universitäten",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 104,
    "short": "Universität Hamburg",
    "name": "Universität Hamburg",
    "type": "Universitäten",
    "state": "Hamburg"
  },
  {
    "id": 119,
    "short": "Universität Heidelberg",
    "name": "Ruprecht-Karls-Universität Heidelberg",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 127,
    "short": "Universität Hildesheim",
    "name": "Universität Hildesheim",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 129,
    "short": "Universität Hohenheim",
    "name": "Universität Hohenheim",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 133,
    "short": "Universität Jena",
    "name": "Friedrich-Schiller-Universität Jena",
    "type": "Universitäten",
    "state": "Thüringen"
  },
  {
    "id": 142,
    "short": "Universität Kassel",
    "name": "Universität Kassel",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 146,
    "short": "Universität Koblenz",
    "name": "Universität Koblenz",
    "type": "Universitäten",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 154,
    "short": "Universität Konstanz",
    "name": "Universität Konstanz",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 159,
    "short": "Universität Leipzig",
    "name": "Universität Leipzig",
    "type": "Universitäten",
    "state": "Sachsen"
  },
  {
    "id": 172,
    "short": "Universität Magdeburg",
    "name": "Otto-von-Guericke-Universität Magdeburg",
    "type": "Universitäten",
    "state": "Sachsen-Anhalt"
  },
  {
    "id": 174,
    "short": "Universität Mainz",
    "name": "Johannes Gutenberg-Universität Mainz",
    "type": "Universitäten",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 176,
    "short": "Universität Mannheim",
    "name": "Universität Mannheim",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 179,
    "short": "Universität Marburg",
    "name": "Philipps-Universität Marburg",
    "type": "Universitäten",
    "state": "Hessen"
  },
  {
    "id": 191,
    "short": "Universität Münster",
    "name": "Universität Münster",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 209,
    "short": "Universität Oldenburg",
    "name": "Carl von Ossietzky Universität Oldenburg",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 211,
    "short": "Universität Osnabrück",
    "name": "Universität Osnabrück",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 215,
    "short": "Universität Paderborn",
    "name": "Universität Paderborn",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 218,
    "short": "Universität Passau",
    "name": "Universität Passau",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 221,
    "short": "Universität Potsdam",
    "name": "Universität Potsdam",
    "type": "Universitäten",
    "state": "Brandenburg"
  },
  {
    "id": 225,
    "short": "Universität Regensburg",
    "name": "Universität Regensburg",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 233,
    "short": "Universität Rostock",
    "name": "Universität Rostock",
    "type": "Universitäten",
    "state": "Mecklenburg-Vorpommern"
  },
  {
    "id": 245,
    "short": "Universität Siegen",
    "name": "Universität Siegen",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 248,
    "short": "Universität Stuttgart",
    "name": "Universität Stuttgart",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 255,
    "short": "Universität Trier",
    "name": "Universität Trier",
    "type": "Universitäten",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 258,
    "short": "Universität Tübingen",
    "name": "Eberhard Karls Universität Tübingen",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 259,
    "short": "Universität Ulm",
    "name": "Universität Ulm",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  },
  {
    "id": 293,
    "short": "Universität Vechta",
    "name": "Universität Vechta",
    "type": "Universitäten",
    "state": "Niedersachsen"
  },
  {
    "id": 266,
    "short": "Universität Weimar",
    "name": "Bauhaus-Universität Weimar",
    "type": "Universitäten",
    "state": "Thüringen"
  },
  {
    "id": 275,
    "short": "Universität Witten/Herdecke",
    "name": "Private Universität Witten/Herdecke gGmbH",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 276,
    "short": "Universität Würzburg",
    "name": "Julius-Maximilians-Universität Würzburg",
    "type": "Universitäten",
    "state": "Bayern"
  },
  {
    "id": 144,
    "short": "Universität zu Kiel",
    "name": "Christian-Albrechts-Universität zu Kiel",
    "type": "Universitäten",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 147,
    "short": "Universität zu Köln",
    "name": "Universität zu Köln",
    "type": "Universitäten",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 168,
    "short": "Universität zu Lübeck",
    "name": "Universität zu Lübeck",
    "type": "Universitäten",
    "state": "Schleswig-Holstein"
  },
  {
    "id": 335,
    "short": "University of Europe for Applied Sciences",
    "name": "University of Europe for Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 524,
    "short": "University of Labour",
    "name": "University of Labour",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 262,
    "short": "Vinzenz Pallotti University",
    "name": "Vinzenz Pallotti University - kirchlich und staatlich anerkannte wissenschaftliche Hochschule in freier Trägerschaft",
    "type": "Universitäten",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 22,
    "short": "weißensee kunsthochschule berlin",
    "name": "weißensee kunsthochschule berlin",
    "type": "Künstlerische Hochschulen",
    "state": "Berlin"
  },
  {
    "id": 95,
    "short": "Westfälische Hochschule",
    "name": "Westfälische Hochschule Gelsenkirchen, Bocholt, Recklinghausen",
    "type": "Fachhochschulen / HAW",
    "state": "Nordrhein-Westfalen"
  },
  {
    "id": 283,
    "short": "Westsächsische Hochschule",
    "name": "Westsächsische Hochschule Zwickau",
    "type": "Fachhochschulen / HAW",
    "state": "Sachsen"
  },
  {
    "id": 261,
    "short": "WHU Vallendar",
    "name": "WHU - Otto Beisheim School of Management",
    "type": "Universitäten",
    "state": "Rheinland-Pfalz"
  },
  {
    "id": 317,
    "short": "Wilhelm Büchner Hochschule",
    "name": "Wilhelm Büchner Hochschule",
    "type": "Fachhochschulen / HAW",
    "state": "Hessen"
  },
  {
    "id": 515,
    "short": "XU Exponential University of Applied Sciences",
    "name": "XU Exponential University of Applied Sciences",
    "type": "Fachhochschulen / HAW",
    "state": "Brandenburg"
  },
  {
    "id": 351,
    "short": "Zeppelin Universität",
    "name": "Zeppelin Universität - Hochschule zwischen Wirtschaft, Kultur und Politik",
    "type": "Universitäten",
    "state": "Baden-Württemberg"
  }
];
