function errorMessage(e) {
    return e instanceof Error ? e.message : String(e);
}
export async function aiMakePdfBlob(title, text) {
    if (window._ssEnsurePdfExportDeps) {
        await window._ssEnsurePdfExportDeps();
    }
    const jsPDFCtor = (window.jspdf && window.jspdf.jsPDF) || window.jsPDF;
    if (!jsPDFCtor) {
        window.showToast?.('jsPDF missing', 'Could not build PDF');
        return null;
    }
    const h2c = window.html2canvas;
    if (!h2c) {
        window.showToast?.('html2canvas missing', 'Could not render PDF');
        return null;
    }
    const container = document.createElement('div');
    container.style.cssText =
        'position:fixed;left:-9999px;top:0;width:750px;background:#ffffff;color:#1a1a1a;font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:1.75;padding:44px 52px;box-sizing:border-box;z-index:99999;';
    const titleEl = document.createElement('div');
    titleEl.style.cssText =
        'font-size:19px;font-weight:700;color:#5028a0;margin-bottom:10px;padding-bottom:10px;border-bottom:2px solid #2563eb;';
    titleEl.textContent = title;
    container.appendChild(titleEl);
    const contentEl = document.createElement('div');
    contentEl.style.color = '#1a1a1a';
    contentEl.innerHTML = window.renderMarkdown ? window.renderMarkdown(text) : text;
    container.appendChild(contentEl);
    const footer = document.createElement('div');
    footer.style.cssText =
        'margin-top:32px;font-size:10px;color:#aaa;border-top:1px solid #eee;padding-top:8px;';
    footer.textContent = 'Generated by Minallo AI';
    container.appendChild(footer);
    document.body.appendChild(container);
    try {
        await new Promise((r) => {
            setTimeout(r, 60);
        });
        const canvas = await h2c(container, {
            scale: 2,
            useCORS: true,
            backgroundColor: '#ffffff',
            logging: false,
        });
        document.body.removeChild(container);
        const doc = new jsPDFCtor({ unit: 'mm', format: 'a4' });
        const pageW = 210;
        const pageH = 297;
        const margin = 10;
        const imgW = pageW - margin * 2;
        const pageContentH = pageH - margin * 2;
        const pxPerMm = canvas.width / imgW;
        let srcYpx = 0;
        let firstPage = true;
        while (srcYpx < canvas.height) {
            if (!firstPage)
                doc.addPage();
            firstPage = false;
            const sliceHpx = Math.min(Math.round(pageContentH * pxPerMm), canvas.height - srcYpx);
            const sliceCanvas = document.createElement('canvas');
            sliceCanvas.width = canvas.width;
            sliceCanvas.height = sliceHpx;
            const ctx = sliceCanvas.getContext('2d');
            if (ctx) {
                ctx.drawImage(canvas, 0, srcYpx, canvas.width, sliceHpx, 0, 0, canvas.width, sliceHpx);
            }
            doc.addImage(sliceCanvas.toDataURL('image/png'), 'PNG', margin, margin, imgW, sliceHpx / pxPerMm);
            srcYpx += sliceHpx;
        }
        return doc.output('blob');
    }
    catch (e) {
        if (document.body.contains(container))
            document.body.removeChild(container);
        window.showToast?.('PDF error', errorMessage(e));
        return null;
    }
}
export async function aiDownloadPdf(title, text) {
    const blob = await aiMakePdfBlob(title, text);
    if (!blob)
        return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download =
        title
            .slice(0, 60)
            .replace(/[^\w\s-]/g, '')
            .trim() + '.pdf';
    a.click();
    setTimeout(() => {
        URL.revokeObjectURL(url);
    }, 2000);
}
export function ufDestPicker(uid, course, onPick) {
    const overlay = document.createElement('div');
    overlay.style.cssText =
        'position:fixed;inset:0;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;z-index:10001;';
    overlay.addEventListener('click', (e) => {
        if (e.target === overlay)
            overlay.remove();
    });
    const box = document.createElement('div');
    box.style.cssText =
        'background:var(--dp-solid);border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:22px 20px;max-width:340px;width:90%;max-height:75vh;overflow-y:auto;display:flex;flex-direction:column;gap:8px;';
    const hdr = document.createElement('div');
    hdr.style.cssText = 'font-weight:800;font-size:.95rem;color:var(--on-glass);margin-bottom:2px;';
    hdr.textContent = 'Where to export?';
    box.appendChild(hdr);
    const sub = document.createElement('div');
    sub.style.cssText = 'font-size:.78rem;color:var(--on-glass-faint);margin-bottom:6px;';
    sub.textContent = course.name || course.short || '';
    box.appendChild(sub);
    function addOpt(icon, label, onClick) {
        const b = document.createElement('button');
        b.style.cssText =
            'display:flex;align-items:center;gap:10px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--on-glass);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;transition:background .13s;';
        b.innerHTML =
            '<span style="font-size:1.1rem">' + icon + '</span><span style="flex:1">' + label + '</span>';
        b.addEventListener('mouseenter', () => {
            b.style.background = 'rgba(37,99,235,.2)';
        });
        b.addEventListener('mouseleave', () => {
            b.style.background = 'rgba(255,255,255,.06)';
        });
        b.addEventListener('click', () => {
            overlay.remove();
            onClick();
        });
        box.appendChild(b);
    }
    addOpt('📁', 'Course root', () => {
        onPick(null);
    });
    if (window._ufGetFolders) {
        window._ufGetFolders(uid, course).forEach((f) => {
            addOpt('📂', f, () => {
                onPick(f);
            });
        });
    }
    const nb = document.createElement('button');
    nb.style.cssText =
        'display:flex;align-items:center;gap:10px;background:rgba(37,99,235,.08);border:1px dashed rgba(37,99,235,.35);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--purple);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;margin-top:2px;';
    nb.innerHTML = '<span style="font-size:1.1rem">➕</span><span>New folder…</span>';
    nb.addEventListener('click', () => {
        const name = prompt('Folder name:');
        if (!name || !name.trim())
            return;
        if (window._ufCreateFolder)
            window._ufCreateFolder(uid, course, name.trim());
        overlay.remove();
        onPick(name.trim());
    });
    box.appendChild(nb);
    const cancel = document.createElement('button');
    cancel.style.cssText =
        'margin-top:6px;background:transparent;border:none;color:rgba(255,255,255,.35);font-family:Nunito,sans-serif;font-size:.8rem;font-weight:700;cursor:pointer;padding:6px;border-radius:8px;transition:color .13s;';
    cancel.textContent = 'Cancel';
    cancel.addEventListener('mouseenter', () => {
        cancel.style.color = 'rgba(255,255,255,.6)';
    });
    cancel.addEventListener('mouseleave', () => {
        cancel.style.color = 'rgba(255,255,255,.35)';
    });
    cancel.addEventListener('click', () => {
        overlay.remove();
    });
    box.appendChild(cancel);
    overlay.appendChild(box);
    document.body.appendChild(overlay);
}
export function glMoveDestPicker(uid, fromCourse, onPick) {
    const isGL = !!fromCourse.id && fromCourse.id.startsWith('german-');
    if (!isGL) {
        ufDestPicker(uid, fromCourse, (f) => {
            onPick(fromCourse, f);
        });
        return;
    }
    function showFolderPicker(toCourse) {
        const overlay2 = document.createElement('div');
        overlay2.style.cssText =
            'position:fixed;inset:0;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;z-index:10002;';
        overlay2.addEventListener('click', (e) => {
            if (e.target === overlay2)
                overlay2.remove();
        });
        const box2 = document.createElement('div');
        box2.style.cssText =
            'background:var(--dp-solid);border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:22px 20px;max-width:340px;width:90%;max-height:75vh;overflow-y:auto;display:flex;flex-direction:column;gap:8px;';
        const topRow = document.createElement('div');
        topRow.style.cssText = 'display:flex;align-items:center;gap:8px;margin-bottom:2px;';
        const backBtn = document.createElement('button');
        backBtn.style.cssText =
            'background:transparent;border:none;color:rgba(255,255,255,.5);font-family:Nunito,sans-serif;font-size:.8rem;font-weight:800;cursor:pointer;padding:4px 8px;border-radius:8px;transition:all .13s;flex-shrink:0;';
        backBtn.textContent = '← Back';
        backBtn.addEventListener('mouseenter', () => {
            backBtn.style.color = 'rgba(255,255,255,.85)';
            backBtn.style.background = 'rgba(255,255,255,.08)';
        });
        backBtn.addEventListener('mouseleave', () => {
            backBtn.style.color = 'rgba(255,255,255,.5)';
            backBtn.style.background = 'transparent';
        });
        backBtn.addEventListener('click', () => {
            overlay2.remove();
            showCardPicker();
        });
        const h2 = document.createElement('div');
        h2.style.cssText = 'font-weight:800;font-size:.95rem;color:var(--on-glass);flex:1;';
        h2.textContent = 'Folder in ' + (toCourse.name || toCourse.id);
        topRow.appendChild(backBtn);
        topRow.appendChild(h2);
        box2.appendChild(topRow);
        function addOpt2(icon, label, onClick) {
            const b = document.createElement('button');
            b.style.cssText =
                'display:flex;align-items:center;gap:10px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--on-glass);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;transition:background .13s;';
            b.innerHTML =
                '<span style="font-size:1.1rem">' +
                    icon +
                    '</span><span style="flex:1">' +
                    label +
                    '</span>';
            b.addEventListener('mouseenter', () => {
                b.style.background = 'rgba(37,99,235,.2)';
            });
            b.addEventListener('mouseleave', () => {
                b.style.background = 'rgba(255,255,255,.06)';
            });
            b.addEventListener('click', () => {
                overlay2.remove();
                onClick();
            });
            box2.appendChild(b);
        }
        addOpt2('📁', 'Root (no folder)', () => {
            onPick(toCourse, null);
        });
        if (window._ufGetFolders) {
            window._ufGetFolders(uid, toCourse).forEach((f) => {
                addOpt2('📂', f, () => {
                    onPick(toCourse, f);
                });
            });
        }
        const nb2 = document.createElement('button');
        nb2.style.cssText =
            'display:flex;align-items:center;gap:10px;background:rgba(37,99,235,.08);border:1px dashed rgba(37,99,235,.35);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--purple);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;margin-top:2px;';
        nb2.innerHTML = '<span style="font-size:1.1rem">➕</span><span>New folder…</span>';
        nb2.addEventListener('click', () => {
            const name = prompt('Folder name:');
            if (!name || !name.trim())
                return;
            if (window._ufCreateFolder)
                window._ufCreateFolder(uid, toCourse, name.trim());
            overlay2.remove();
            onPick(toCourse, name.trim());
        });
        box2.appendChild(nb2);
        overlay2.appendChild(box2);
        document.body.appendChild(overlay2);
    }
    function showCardPicker() {
        const overlay = document.createElement('div');
        overlay.style.cssText =
            'position:fixed;inset:0;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;z-index:10001;';
        overlay.addEventListener('click', (e) => {
            if (e.target === overlay)
                overlay.remove();
        });
        const box = document.createElement('div');
        box.style.cssText =
            'background:var(--dp-solid);border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:22px 20px;max-width:340px;width:90%;max-height:75vh;overflow-y:auto;display:flex;flex-direction:column;gap:8px;';
        const hdr = document.createElement('div');
        hdr.style.cssText = 'font-weight:800;font-size:.95rem;color:var(--on-glass);margin-bottom:2px;';
        hdr.textContent = 'Move to…';
        box.appendChild(hdr);
        const sub = document.createElement('div');
        sub.style.cssText = 'font-size:.78rem;color:var(--on-glass-faint);margin-bottom:6px;';
        sub.textContent = 'Pick a destination card';
        box.appendChild(sub);
        const glSkillNames = window._glSkillNames || {};
        Object.keys(glSkillNames).forEach((sk) => {
            const c = {
                id: 'german-' + sk,
                short: 'german-' + sk,
                name: 'German ' + glSkillNames[sk],
            };
            const isCurrent = c.id === fromCourse.id;
            const b = document.createElement('button');
            b.style.cssText =
                'display:flex;align-items:center;gap:10px;background:' +
                    (isCurrent ? 'rgba(37,99,235,.18)' : 'rgba(255,255,255,.06)') +
                    ';border:1px solid ' +
                    (isCurrent ? 'rgba(37,99,235,.4)' : 'rgba(255,255,255,.1)') +
                    ';border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--on-glass);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;transition:background .13s;';
            b.innerHTML =
                '<span style="font-size:1.1rem">📚</span><span style="flex:1">' +
                    glSkillNames[sk] +
                    (isCurrent ? ' (current)' : '') +
                    '</span>';
            b.addEventListener('mouseenter', () => {
                b.style.background = 'rgba(37,99,235,.25)';
            });
            b.addEventListener('mouseleave', () => {
                b.style.background = isCurrent ? 'rgba(37,99,235,.18)' : 'rgba(255,255,255,.06)';
            });
            b.addEventListener('click', () => {
                overlay.remove();
                showFolderPicker(c);
            });
            box.appendChild(b);
        });
        const cancel = document.createElement('button');
        cancel.style.cssText =
            'margin-top:6px;background:transparent;border:none;color:rgba(255,255,255,.35);font-family:Nunito,sans-serif;font-size:.8rem;font-weight:700;cursor:pointer;padding:6px;border-radius:8px;transition:color .13s;';
        cancel.textContent = 'Cancel';
        cancel.addEventListener('mouseenter', () => {
            cancel.style.color = 'rgba(255,255,255,.6)';
        });
        cancel.addEventListener('mouseleave', () => {
            cancel.style.color = 'rgba(255,255,255,.35)';
        });
        cancel.addEventListener('click', () => {
            overlay.remove();
        });
        box.appendChild(cancel);
        overlay.appendChild(box);
        document.body.appendChild(overlay);
    }
    showCardPicker();
}
export async function aiExportToCourse(title, text, course, _folder) {
    if (!course) {
        window.showToast?.('No course', 'Open a course first');
        return;
    }
    const uid = window._currentUser && (window._currentUser.id || window._currentUser.sub);
    if (!uid) {
        window.showToast?.('Not logged in', 'Please sign in first');
        return;
    }
    if (_folder === undefined) {
        ufDestPicker(uid, course, (picked) => {
            void aiExportToCourse(title, text, course, picked);
        });
        return;
    }
    const blob = await aiMakePdfBlob(title, text);
    if (!blob)
        return;
    const fname = title
        .slice(0, 50)
        .replace(/[^\w\s-]/g, '')
        .trim() + '.pdf';
    const file = new File([blob], fname, { type: 'application/pdf' });
    try {
        if (!window._ufUpload) {
            window.showToast?.('Upload missing', 'Storage helper not loaded');
            return;
        }
        await window._ufUpload(uid, course, file, null, _folder || null);
        const dest = _folder
            ? '"' + _folder + '" in ' + (course.name || course.short || '')
            : course.name || course.short || '';
        window.showToast?.('Exported ✓', fname + ' added to ' + dest);
    }
    catch (e) {
        window.showToast?.('Export failed', errorMessage(e));
    }
}
export function aiShowExportModal(title, text) {
    const modal = document.getElementById('aiExportModal');
    const list = document.getElementById('aiExportCourseList');
    const status = document.getElementById('aiExportStatus');
    if (!modal || !list || !status)
        return;
    status.textContent = '';
    list.innerHTML = '';
    const allCourses = [];
    Object.values(window.SEMS || {}).forEach((sem) => {
        (sem.courses || []).forEach((c) => {
            allCourses.push(c);
        });
    });
    if (!allCourses.length) {
        list.innerHTML =
            '<p style="color:var(--on-glass-muted);font-size:.85rem">No courses found.</p>';
    }
    else {
        allCourses.forEach((course) => {
            const btn = document.createElement('button');
            btn.style.cssText =
                'display:flex;align-items:center;gap:10px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--on-glass);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;transition:background .13s;width:100%';
            btn.innerHTML =
                '<span style="font-size:1.1rem">📚</span><span style="flex:1">' +
                    (course.name || course.short) +
                    '</span>';
            btn.addEventListener('mouseenter', () => {
                btn.style.background = 'rgba(37,99,235,.2)';
            });
            btn.addEventListener('mouseleave', () => {
                btn.style.background = 'rgba(255,255,255,.06)';
            });
            btn.addEventListener('click', () => {
                btn.disabled = true;
                const uid = window._currentUser && (window._currentUser.id || window._currentUser.sub);
                if (!uid) {
                    status.textContent = '⚠️ Not signed in';
                    return;
                }
                modal.style.display = 'none';
                ufDestPicker(uid, course, async (folder) => {
                    modal.style.display = 'flex';
                    status.textContent = '⏳ Uploading…';
                    await aiExportToCourse(title, text, course, folder);
                    status.textContent = '✓ Done!';
                    setTimeout(() => {
                        modal.style.display = 'none';
                        status.textContent = '';
                    }, 1200);
                });
            });
            list.appendChild(btn);
        });
    }
    modal.style.display = 'flex';
}
export function aiResponseActions(rawText, context) {
    let title = '';
    const headingMatch = rawText.match(/^#{1,3} (.+)/m);
    if (headingMatch && headingMatch[1]) {
        title = headingMatch[1].trim();
    }
    else {
        const firstLine = rawText
            .replace(/^[\s\n]+/, '')
            .split('\n')[0]
            .replace(/\*\*/g, '')
            .trim();
        title = firstLine.length > 60 ? firstLine.slice(0, 60) + '…' : firstLine;
    }
    if (!title)
        title = 'AI Response';
    const bar = document.createElement('div');
    bar.className = 'ai-action-bar';
    const dlBtn = document.createElement('button');
    dlBtn.className = 'ai-action-btn';
    dlBtn.innerHTML =
        '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg> Download PDF';
    dlBtn.addEventListener('click', () => {
        void aiDownloadPdf(title, rawText);
    });
    const expBtn = document.createElement('button');
    expBtn.className = 'ai-action-btn';
    expBtn.innerHTML =
        '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/><line x1="12" y1="11" x2="12" y2="17"/><line x1="9" y1="14" x2="15" y2="14"/></svg> Export to course';
    expBtn.addEventListener('click', () => {
        if (context === 'panel') {
            void aiExportToCourse(title, rawText, window.activeCourseRef);
        }
        else {
            aiShowExportModal(title, rawText);
        }
    });
    bar.appendChild(dlBtn);
    bar.appendChild(expBtn);
    return bar;
}
//# sourceMappingURL=ai-export.js.map